// import type { Metadata } from "next";
// import { AntdRegistry } from "@ant-design/nextjs-registry";
// import "./globals.scss";
// import Sibar from "./Components/Sibar/Sibar";
// import Body from "./Components/Body/Body";

// export const metadata: Metadata = {
//   title: "Music App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`antialiased`}>
//         <AntdRegistry>{children}</AntdRegistry>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.scss";
import Sibar from "./Components/Sibar/Sibar";
import Body from "./Components/Body/Body";
import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header/Header";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div
          className="flex"
          style={{ height: "", backgroundColor: "#170f23" }}
        >
          <div
            className="w-1/5"
            style={{
              height: "100%",
              backgroundColor: "rgba(255, 255, 255, 0.05)",
            }}
          >
            <Sibar />
          </div>
          <div
            className="w-4/5"
            style={{ height: "100vh", overflowY: "scroll" }}
          >
            <Header />
            <AntdRegistry>{children}</AntdRegistry>
          </div>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
