"use client";
import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.scss";
import Sibar from "./Components/Sibar/Sibar";
import Body from "./Components/Body/Body";
import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header/Header";
import Link from "next/link";
import Head from "next/head";
import PlayerMusic from "./Components/Body/PlayerMusic";
import { Provider } from "react-redux";
import { store } from "./reudx/store";
import { MusicPlayerProvider } from "@/context/MusicPlayerContext";
import { useRouter } from "next/router";
// import { metadata } from "./metadata";
import useDebounce from "./Components/Hooks/useDebounce";
import { useEffect, useState } from "react";
import MobieIU from "./Components/mobieUI/MobieIU";

// export const metadata: Metadata = {
//   title: "Music App",
//   description: "Generated by create next app",
// };
// export { metadata };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [windowWidth, setWindowWidth] = useState<number>(window.innerWidth);

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);
  const deBounceResizeWidth = useDebounce(windowWidth, 300);

  return (
    <html lang="en">
      <head>
        <Head>
          <title>Music App</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
      </head>
      {/* <title>Music App</title> */}
      <body className={`antialiased`}>
        <Provider store={store}>
          <MusicPlayerProvider>
            {/* <div className="">
              <div
                className="flex"
                style={{ height: "", backgroundColor: "#170f23" }}
              >
                <div
                  className="w-1/5"
                  style={{
                    height: "100%",
                    backgroundColor: "rgba(255, 255, 255, 0.05)",
                  }}
                >
                  <Sibar />
                </div>
                <div
                  className="w-4/5"
                  style={{ height: "100vh", overflowY: "scroll" }}
                >
                  <Header />
                  <AntdRegistry>{children}</AntdRegistry>
                </div>
                <div className="player">
                  <div className="">
                    <PlayerMusic />
                  </div>
                </div>
              </div>
             
            </div> */}
            {deBounceResizeWidth > 1100 ? (
              <div className="">
                <div
                  className="flex"
                  style={{ height: "", backgroundColor: "#170f23" }}
                >
                  <div
                    className="w-1/5"
                    style={{
                      height: "100%",
                      backgroundColor: "rgba(255, 255, 255, 0.05)",
                    }}
                  >
                    <Sibar />
                  </div>
                  <div
                    className="w-4/5"
                    style={{ height: "100vh", overflowY: "scroll" }}
                  >
                    <Header />
                    <AntdRegistry>{children}</AntdRegistry>
                  </div>
                  <div className="player">
                    <div className="">
                      <PlayerMusic />
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <MobieIU />
            )}
          </MusicPlayerProvider>
        </Provider>
      </body>
    </html>
  );
}
